#define BAR_LTSYMBOL_PATCH 1
#define BAR_STATUS_PATCH 1
#define BAR_TAGS_PATCH 1
#define BAR_WINTITLE_PATCH 1
#define BAR_ALPHA_PATCH 1
#define BAR_ANYBAR_PATCH 1
#define BAR_EWMHTAGS_PATCH 1
#define BAR_HIDEVACANTTAGS_PATCH 1
#define BAR_IGNORE_XFT_ERRORS_WHEN_DRAWING_TEXT_PATCH 1
#define BAR_STATUSALLMONS_PATCH 1
#define BAR_STATUS2D_PATCH 1

#define ALWAYSCENTER_PATCH 1
#define AUTOSTART_PATCH 1
#define DECORATION_HINTS_PATCH 1
#define IPC_PATCH 1
#define NOBORDER_PATCH 1
#define RESIZEPOINT_PATCH 1
#define RESTARTSIG_PATCH 1
#define VANITYGAPS_PATCH 1

#define TILE_LAYOUT 1
#define MONOCLE_LAYOUT 1
