font:
  size: 10

schemes:
  iterm: &iterm
    primary:
      background: '#101421'
      foreground: '#fffbf6'
    normal:
      black:   '#2e2e2e'
      red:     '#eb4129'
      green:   '#8be027'
      yellow:  '#f6c744'
      blue:    '#47a0f3'
      magenta: '#7b5cb0'
      cyan:    '#64dbed'
      white:   '#e5e9f0'
    bright:
      black:   '#565656'
      red:     '#ec5357'
      green:   '#c0f15d'
      yellow:  '#f9da6a'
      blue:    '#49a4f8'
      magenta: '#a47de9'
      cyan:    '#99faf2'
      white:   '#ffffff'
  solarized_light: &solarized_light
    primary:
      background: '#fdf6e3' # base3
      foreground: '#657b83' # base00
    cursor:
      text:   '#fdf6e3' # base3
      cursor: '#657b83' # base00
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3
  ayu_dark: &ayu_dark
    primary:
      background: '0x0A0E14'
      foreground: '0xB3B1AD'
    normal:
      black:   '0x01060E'
      red:     '0xEA6C73'
      green:   '0x91B362'
      yellow:  '0xF9AF4F'
      blue:    '0x53BDFA'
      magenta: '0xFAE994'
      cyan:    '0x90E1C6'
      white:   '0xC7C7C7'
    bright:
      black:   '0x686868'
      red:     '0xF07178'
      green:   '0xC2D94C'
      yellow:  '0xFFB454'
      blue:    '0x59C2FF'
      magenta: '0xFFEE99'
      cyan:    '0x95E6CB'
      white:   '0xFFFFFF'

colors: *iterm

